name:                twitanalysis
version:             0.1.0.0
github:              "easoncxz/twitanalysis"
license:             AllRightsReserved
author:              "easoncxz"
maintainer:          "easoncxz@gmail.com"
copyright:           "2020 easoncxz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/twitanalysis#readme>

dependencies:
- aeson
- base >= 4.7 && < 5
- base64-bytestring
- blaze-html
- blaze-markup
- bytestring
- containers
- crypto-api
- hspec
- http-client
- http-client-tls
- http-types
- microlens
- oauthenticated
- scotty
- stm
- time
- text
- twitter-types
- unordered-containers
- wai
- wai-extra
- wai-middleware-static

library:
  source-dirs: src

executables:
  twitanalysis-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twitanalysis

tests:
  twitanalysis-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - twitanalysis
