name: Main Workflow
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # https://github.com/actions/setup-node/
      - uses: actions/setup-node@v2-beta
        with:
          # should match frontend-app/.node-version
          node-version: '14.9.0'

      # https://github.com/actions/setup-ruby
      - uses: actions/setup-ruby@v1
        with:
          # should match .ruby-version
          ruby-version: '2.7'

      - name: 'which node'
        run: 'which node && node --version'
        shell: bash

      - name: 'which ruby'
        run: 'which ruby && ruby --version'
        shell: bash

      - name: 'Install Bundler'
        run: './activate.sh gem install bundler'
        shell: bash

      - name: 'Build, test, and package'
        run: './activate.sh bundle exec rake'
        shell: bash

        # Docs:
        #
        #   - event_name: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#contexts
        #
        #   - create event: https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#create
      - name: 'Publish as Github Release'
        run: "./activate.sh bundle exec rake 'publish[${{ github.event.ref }}]'"
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        env:
          # Convert Github's env-var into one understook by my Rakefile
          #
          # Docs:
          #   - https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#github-context
          GITHUB_OAUTH_TOKEN: "${{ github.token }}"
