name: Daily Workflow
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      # https://github.com/actions/setup-node/
      - name: Set NodeJS version
        uses: actions/setup-node@v2-beta
        with:
          # should match frontend-app/.node-version
          node-version: '14.9.0'

      # https://github.com/actions/setup-ruby
      - name: Set Ruby version
        uses: actions/setup-ruby@v1
        with:
          # should match .ruby-version
          ruby-version: '2.7'

      - name: 'which node'
        run: 'which node && node --version'
        shell: bash

      - name: 'which ruby'
        run: 'which ruby && ruby --version'
        shell: bash

      - name: Cache for Ruby Gems
        uses: actions/cache@v2
        with:
          path: .gems
          key: ${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}

      - name: 'Install Bundler and Gems'
        run: |
          ./activate.sh gem install bundler
          ./activate.sh bundle install
        shell: bash

      - name: Cache for Haskell Stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack/
            backend-app/.stack-work/
          key: ${{ runner.os }}-${{ hashFiles('backend-app/package.yaml', 'backend-app/stack.yaml') }}

      - name: 'Run Rake: default'
        run: './activate.sh bundle exec rake'
        shell: bash
