name: Main Github Actions Workflow
on:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # https://github.com/actions/setup-node/
      - uses: actions/setup-node@v2-beta
        with:
          # should match frontend-app/.node-version
          node-version: '14.9.0'

      # https://github.com/actions/setup-ruby
      - uses: actions/setup-ruby@v1
        with:
          # should match .ruby-version
          ruby-version: '2.7'

      - name: 'which node'
        run: 'which node && node --version'
        shell: bash

      - name: 'which ruby'
        run: 'which ruby && ruby --version'
        shell: bash
