name: Daily Workflow
on:
  push:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY_TO_VULTR }}
          name: twitanalysis-github-action-runner
          known_hosts: |
            twitanalysis.easoncxz.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBAYuwrY53sBSdWXvVUiFfwf0QSKhNVdSDZ96Hzl0acW1RMlS2dMdkdH1ajTon/qGCdw5A8/Onx+nJX+zAZ2lzw0=
          config: |
            Host twitanalysis.easoncxz.com
                HostName twitanalysis.easoncxz.com
                User eason
                IdentityFile ~/.ssh/twitanalysis-github-action-runner
                IdentitiesOnly yes
                PasswordAuthentication no
                ForwardAgent no

      # https://github.com/actions/setup-node/
      - name: Set NodeJS version
        uses: actions/setup-node@v2-beta
        with:
          # should match frontend-app/.node-version
          node-version: '14.9.0'

      # https://github.com/actions/setup-ruby
      - name: Set Ruby version
        uses: actions/setup-ruby@v1
        with:
          # should match .ruby-version
          ruby-version: '2.7'

      - name: 'which node'
        run: 'which node && node --version'
        shell: bash

      - name: 'which ruby'
        run: 'which ruby && ruby --version'
        shell: bash

      - name: Cache for Ruby Gems
        uses: actions/cache@v2
        with:
          path: .gems
          key: ${{ runner.os }}-${{ hashFiles('Gemfile.lock') }}

      - name: 'Install Bundler and Gems'
        run: |
          ./activate.sh gem install bundler
          ./activate.sh bundle install
        shell: bash

      - name: Cache for Haskell Stack
        uses: actions/cache@v2
        with:
          path: |
            ~/.stack/
            backend-app/.stack-work/
          key: ${{ runner.os }}-${{ hashFiles('backend-app/package.yaml', 'backend-app/stack.yaml') }}

      # Like a proper publish, but without a Git tag
      - name: 'Run Rake: publish (untagged)'
        run: "./activate.sh bundle exec rake publish"
        env:
          GITHUB_OAUTH_TOKEN: "${{ github.token }}"

      - name: Deploy to Vultr
        run: "./activate.sh bundle exec rake deploy"
